-- DBMS_UTILITY
SET SERVEROUTPUT ON

EXECUTE DBMS_UTILITY.GET_DEPENDENCY('TABLE', 'HR', 'PRUEBA');

EXECUTE DBMS_UTILITY.VALIDATE('HR', 'PRUEBA', 1);

/*
1 = TABLE/PROCEDURE/TYPE;
2 = BODY
3 = TRIGGER
4 = INDEX
5 = CLUSTER
8 = LOB
9 = DIRECTORY
10 = QUEUE*/

EXECUTE DBMS_UTILITY.COMPILE_SCHEMA('HR', COMPILE_ALL=>FALSE, REUSE_SETTINGS=>TRUE);