-- GRANT CREATE ANY DIRECTORY TO HR; -- COMO SYS DAR PERMISSÃO DE CIAR OU LER E ESCRITA
-- GRANT READ ON DIRECTORY FICHEROS TO HR;
CREATE OR REPLACE DIRECTORY FICHEROS
AS 'C:\Users\Jr\Pictures\FICHEROS_LOB';

SELECT * FROM ALL_DIRECTORIES;