ALTER SESSION SET PLSQL_CODE_TYPE='INTERPRETED';
/

CREATE OR REPLACE PROCEDURE EJEMPLO AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('EXEMPLO');
END;
/

SELECT * FROM USER_PLSQL_OBJECT_SETTINGS WHERE NAME LIKE 'EJEMPLO';

ALTER SESSION SET PLSQL_CODE_TYPE='NAME';
/