SET SERVEROUTPUT ON
DECLARE
    TYPE DEPARTAMENTOS IS TABLE OF DEPATMENTS.DEPARTMENT_NAME%TYPE
        INDEX BY PLS_INTEGER;
        
    DEPTS DEPARTAMENTOS;
    
    TYPE EMPLEADOS IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY PLS_INTEGER;
BEGIN
    NULL;
END;