--SELECT * FROM CLIENTES;

CREATE OR REPLACE PROCEDURE CARGA_CLIENTES
IS
    CURSOR CLI IS SELECT * FROM CLIENTES FOR UPDATE;
    FICHERO VARCHAR2(100);
BEGIN
    FOR C1 IN CLI LOOP
        FICHERO := 'cliente'||C1.CODIGO||'.jpg';
        UPDATE CLIENTES SET FOTO=BFILENAME('FICHEROS',FICHERO),LONGITUD=TAM('FICHEROS',C1.CODIGO)
            WHERE CURRENT OF CLI;
    END LOOP;
END;
/

EXECUTE CARGA_CLIENTES;

SELECT * FROM CLIENTES;
