-- EXECUTE IMMEDIATE CADENA
/*
    CREATE TABLE NOM (V1 NUMBER, V2 VARCHAR2(200));
*/

CREATE OR REPLACE PROCEDURE CREAR_TABLA (NOMBRE_TABLA VARCHAR2, COLUMNAS VARCHAR2)
AUTHID CURRENT_USER --DEFINER
IS
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE '|| NOMBRE_TABLA ||'('||COLUMNAS||')';
END;
/

BEGIN
    CREAR_TABLA('PR2', 'CODIGO NUMBER, DATOS VARCHAR2(100)');
END;
/
